version: "3.9"
services:
  caddy:
    image: jaidchen/caddy
    restart: unless-stopped
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - ./volume/Caddyfile:/etc/caddy/Caddyfile
      - ./volume/static:/usr/share/caddy
    environment:
      - cloudflareApiToken # Forwared from host to container